openapi: 3.0.0
info:
  title: Hot Totties
  description: Base user API for LMS
  version: 1.0.0
servers:
  - url: http://api-lms.com
    description: Optional server description, e.g. Main (production) server
  - url: http://localhost:8080
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /user:
    get:
      summary: Returns a user.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: userId
          in: query
          required: true
          description: Users name
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: User was found
          content:
            application/json:
              schema: 
                type: string
                items: 
                  type: string
  /user/createUser:
      post:
        summary: Create a single user
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  firstname:
                    type: string
                  lastname:
                    type: string
                  email:
                    type: string
        responses:
          '201':
            description: User was created
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    username:
                      type: string
                    firstname:
                      type: string
                    lastname:
                      type: string
                    email:
                      type: string
          '400':
            description: User was not created
         
          default:
            description: unexpected error
  /users/updateUser:
    put:
      summary: Update a user
      description: user creation
      responses:
        '200':
          description: user successfully updated
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string